spring:
  threads:
    virtual:
      enabled: true
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

logging:
  pattern:
    level: "%5p %X{X-Correlation-ID:--}"

messaging:
  message-processor:
    inbound-retry-message-expiry-duration: "${INBOUND_RETRY_EXPIRY:PT20S}"
    inbound-retry-delay-duration: "${INBOUND_RETRY_DELAY:PT2S}"
    inbound-retry-delay-multiplication-factor: "${INBOUND_RETRY_MULTIPLICATION:2}"