spring:
  threads:
    virtual:
      enabled: true
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
#          max-attempts: 3
#          initial-interval: "1000ms"

logging:
  pattern:
    level: "%5p %X{X-Correlation-ID:--}"

messaging:
  message-processor:
    inbound-retry-message-expiry-duration: "${INBOUND_RETRY_EXPIRY:PT20S}"
    inbound-retry-delay-duration: "${INBOUND_RETRY_DELAY:PT2S}"
    inbound-retry-delay-multiplication-factor: "${INBOUND_RETRY_MULTIPLICATION:2}"